[package]
name = "bots"
version = "0.1.0"
authors = ["Andrew <andrew@egeler.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]

[build-dependencies]
cbindgen = "0.19.0"
